### ISSUE TITLE
Cannot read property 'shape' of undefined

### ISSUE THREAD

**Issue by latusaki** [facebook/prop-types#120]
I am getting this error,

TypeError: Cannot read property 'shape' of undefined

   at Object.<anonymous> (node_modules/react-native-deprecated-custom-components/src/NavigatorBreadcrumbNavigationBar.js:300:425)
   at Object.<anonymous> (node_modules/react-native-deprecated-custom-components/src/Navigator.js:44:38)
   at Object.<anonymous> (node_modules/react-native-deprecated-custom-components/src/CustomComponents.js:28:15)

    "prop-types": "^15.6.0",
    "react": "=16.0.0",
    "react-native-deprecated-custom-components": "=0.1.1",
    "react-native": "=0.48.4",

Not sure if this is an issue with the old Navigator, or PropTypes, commented on a ticket there as well. 
Any suggestions on how to deal with it ?

https://github.com/facebookarchive/react-native-custom-components/issues/16

**Comment by latusaki** [comment]
Hm looks like this exists already...
https://github.com/facebook/prop-types/blob/01634d92e4e4cb5ffaf7de96ea8cb5da9b65e4f0/__tests__/PropTypesProductionReact15-test.js#L216

**Comment by latusaki** [comment]
Just noticed Navigator is using both external proptypes and react...

 ```
   routeMapper: PropTypes.shape({
      rightContentForRoute: PropTypes.func,
      titleContentForRoute: PropTypes.func,
      iconForRoute: PropTypes.func,
    }),
    navState: React.PropTypes.shape({
```
